# Generated by Django 4.1.3 on 2023-01-03 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_pic',
            new_name='Profile',
        ),
    ]
